declare const _default: typeof __VLS_export;
export default _default;
declare const __VLS_export: import("vue").DefineComponent<{}, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {
    PaletteGenerator: import("vue").DefineComponent<{}, {
        palette: import("vue").Ref<any[], any[]>;
        colorCount: import("vue").Ref<number, number>;
        displayFormat: import("vue").Ref<string, string>;
        pinnedColors: import("vue").Ref<Set<any> & Omit<Set<any>, keyof Set<any>>, Set<any> | (Set<any> & Omit<Set<any>, keyof Set<any>>)>;
        showCopyNotification: import("vue").Ref<boolean, boolean>;
        paletteType: import("vue").Ref<string, string>;
        moodType: import("vue").Ref<string, string>;
        baseColor: import("vue").Ref<string, string>;
        savedPalettes: import("vue").Ref<any[], any[]>;
        paletteName: import("vue").Ref<string, string>;
        paletteTags: import("vue").Ref<string, string>;
        searchQuery: import("vue").Ref<string, string>;
        showOnlyFavorites: import("vue").Ref<boolean, boolean>;
        exportFormat: import("vue").Ref<string, string>;
        exportTitles: {
            css: string;
            scss: string;
            tailwind: string;
            json: string;
        };
        exportedCode: import("vue").ComputedRef<string>;
        showColorWheel: import("vue").Ref<boolean, boolean>;
        colorWheelCanvas: import("vue").Ref<any, any>;
        editingColorIndex: import("vue").Ref<any, any>;
        editingColor: import("vue").Ref<string, string>;
        contrastCombinations: import("vue").ComputedRef<{
            fg: any;
            bg: any;
            ratio: string;
            levelAA: boolean;
            levelAAA: boolean;
        }[]>;
        suggestedAccents: import("vue").ComputedRef<string[]>;
        filteredPalettes: import("vue").ComputedRef<any[]>;
        generatePalette: () => void;
        generateFromBase: () => void;
        updateBaseColor: () => void;
        getColorValue: (color: any) => any;
        copyToClipboard: (text: any) => Promise<void>;
        togglePin: (index: any) => void;
        editColor: (index: any) => void;
        saveEditedColor: () => void;
        closeEdit: () => void;
        savePalette: () => void;
        loadPalette: () => void;
        applyPalette: (saved: any) => void;
        editSavedPalette: (saved: any) => void;
        removeSavedPalette: (id: any) => void;
        toggleFavorite: (id: any) => void;
        toggleFavorites: () => void;
        addAccentToPalette: (accent: any) => void;
        copyCodeToClipboard: () => Promise<void>;
        drawColorWheel: () => void;
    }, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
